"""
scary-auntie: Verified Alaskan Native Botanical Seed Data
Prepopulated from authoritative ethnobotanical sources.
All entries include source attribution for scraped/cited information.
Author: scary-auntie project

Sources:
- Garibaldi, Ann. "Medicinal Flora of the Alaska Natives." 1999.
- Kari, Priscilla Russell. "Tanaina Plantlore." 1987.
- Jones, Anore. "Nauriat Niginaqtuat: Plants That We Eat." 1983.
- Schofield, Janice J. "Alaska's Wild Plants." 1993.
- USFS Alaska Region Traditional Ecological Knowledge.
"""

from database import add_plant


def seed_verified_plants():
    """Prepopulate the database with verified Alaskan Native botanicals."""

    plants = [
        # --- BERRIES ---
        {
            "latin_binomial": "Rubus chamaemorus",
            "english_name": "Cloudberry / Salmonberry (baked)",
            "native_alaskan_name": "Aqpik (Yupik); Akpiq (Inupiaq)",
            "native_language": "Yupik, Inupiaq",
            "family": "Rosaceae",
            "description": "Low-growing perennial herb with white flowers and amber-colored berries. Found in tundra and boreal forest bogs.",
            "habitat": "Tundra bogs, wet meadows, boreal forest understory",
            "traditional_uses": "Eaten fresh, preserved in seal oil, or mixed with fat. Used for vitamin C during long winters. Leaves used for tea.",
            "parts_used": "Berries, leaves",
            "preparation": "Berries eaten raw, in akutaq (Eskimo ice cream), or preserved in oil. Leaves dried for tea.",
            "cautions": "None known. Safe food plant.",
            "verified": True,
            "source_author": "Kari, Priscilla Russell; Jones, Anore",
            "source_url": "https://www.fs.usda.gov/Internet/FSE_DOCUMENTS/stelprdb5202434.pdf"
        },
        {
            "latin_binomial": "Vaccinium uliginosum",
            "english_name": "Bog Blueberry / Alpine Blueberry",
            "native_alaskan_name": "Cugaq (Yupik); Paunnaq (Inupiaq)",
            "native_language": "Yupik, Inupiaq",
            "family": "Ericaceae",
            "description": "Low shrub with small blue-black berries growing in alpine and boggy areas. Important subsistence food across Alaska.",
            "habitat": "Alpine tundra, bogs, acidic soils",
            "traditional_uses": "Major subsistence food. Dried for winter storage. Leaves used as tea. Berries have mild laxative properties.",
            "parts_used": "Berries, leaves",
            "preparation": "Eaten fresh, dried, or in akutaq. Leaf tea steeped like black tea.",
            "cautions": "None known.",
            "verified": True,
            "source_author": "Jones, Anore; Schofield, Janice J.",
            "source_url": "https://www.uaf.edu/ces/"
        },
        {
            "latin_binomial": "Rubus spectabilis",
            "english_name": "Salmonberry",
            "native_alaskan_name": "Nunakaat (Tlingit); Nuvvakkat (Alutiiq)",
            "native_language": "Tlingit, Alutiiq",
            "family": "Rosaceae",
            "description": "Tall shrub with pink-purple flowers and raspberry-like orange or red berries. Found in Southeast Alaska coastal forests.",
            "habitat": "Coastal temperate rainforest, streambanks, forest edges",
            "traditional_uses": "Berries eaten fresh or dried. Young shoots peeled and eaten raw. Bark used medicinally by some groups.",
            "parts_used": "Berries, young shoots, bark",
            "preparation": "Berries eaten fresh. Shoots peeled and eaten like asparagus. Bark decoction for digestive complaints.",
            "cautions": "None known.",
            "verified": True,
            "source_author": "Garibaldi, Ann; Kari, Priscilla Russell",
            "source_url": "https://www.nps.gov/articles/ethnobotany-of-southeast-alaska.htm"
        },
        {
            "latin_binomial": "Empetrum nigrum",
            "english_name": "Crowberry",
            "native_alaskan_name": "Pauraq (Yupik); Pauraq (Inupiaq); Kanat'aah (Athabascan)",
            "native_language": "Yupik, Inupiaq, Athabascan (multiple dialects)",
            "family": "Ericaceae",
            "description": "Low evergreen shrub with needle-like leaves and small black berries. Extremely important in Arctic and subarctic regions.",
            "habitat": "Tundra, alpine areas, open woodlands, rocky slopes",
            "traditional_uses": "One of the most important Arctic berries. Eaten fresh, dried, in akutaq, or preserved in seal oil. High in antioxidants.",
            "parts_used": "Berries",
            "preparation": "Eaten fresh or mixed with other berries. Dried for winter. High oil content makes it good for preservation.",
            "cautions": "None known. Very safe and nutritious.",
            "verified": True,
            "source_author": "Jones, Anore; Garibaldi, Ann",
            "source_url": "https://www.uaf.edu/ces/"
        },
        {
            "latin_binomial": "Vaccinium vitis-idaea",
            "english_name": "Lowbush Cranberry / Lingonberry",
            "native_alaskan_name": "Kimminaq (Yupik); Kimmiq (Inupiaq)",
            "native_language": "Yupik, Inupiaq",
            "family": "Ericaceae",
            "description": "Small evergreen shrub with bright red sour berries. Found throughout boreal forest and tundra regions.",
            "habitat": "Boreal forest, tundra, acidic soils",
            "traditional_uses": "Eaten fresh, in sauces, or preserved. Used for urinary tract health. Leaves sometimes used as tea.",
            "parts_used": "Berries, leaves",
            "preparation": "Berries eaten fresh, in akutaq, or preserved in seal oil. Leaf tea for mild urinary discomfort.",
            "cautions": "None known in normal food quantities.",
            "verified": True,
            "source_author": "Schofield, Janice J.",
            "source_url": "https://www.uaf.edu/ces/"
        },

        # --- MEDICINAL PLANTS ---
        {
            "latin_binomial": "Ledum palustre ssp. decumbens",
            "english_name": "Labrador Tea / Hudson Bay Tea",
            "native_alaskan_name": "Cen'ana (Dena'ina); Cena'a (Ahtna)",
            "native_language": "Dena'ina, Ahtna (Athabascan)",
            "family": "Ericaceae",
            "description": "Low aromatic evergreen shrub with leathery leaves and white flowers. One of the most widely used medicinal plants in Alaska.",
            "habitat": "Wet tundra, bogs, open black spruce forests",
            "traditional_uses": "Used for colds, sore throats, stomachaches, and as a general tonic. Topically for skin conditions. Highly regarded medicine across all Alaska Native groups.",
            "parts_used": "Leaves, young shoots",
            "preparation": "Leaves steeped as strong tea. Used fresh or dried. Sometimes combined with other plants.",
            "cautions": "Contains ledol; excessive consumption can cause dizziness or cramps. Not for pregnant women. Do not confuse with toxic look-alikes.",
            "verified": True,
            "source_author": "Kari, Priscilla Russell; Garibaldi, Ann",
            "source_url": "https://www.fs.usda.gov/Internet/FSE_DOCUMENTS/stelprdb5202434.pdf"
        },
        {
            "latin_binomial": "Achillea borealis",
            "english_name": "Yarrow / Boreal Yarrow",
            "native_alaskan_name": "Ggaay (Tlingit); K'elt'ani (Dena'ina)",
            "native_language": "Tlingit, Dena'ina",
            "family": "Asteraceae",
            "description": "Perennial herb with feathery leaves and flat-topped clusters of white flowers. Found across Alaska in open areas.",
            "habitat": "Open meadows, roadsides, disturbed areas, coastal plains",
            "traditional_uses": "Widely used for wounds, bleeding, colds, and fever. Applied as poultice for cuts. Stems used in sweat baths. Stimulates sweating to break fevers.",
            "parts_used": "Leaves, flowers, stems",
            "preparation": "Leaf poultice for wounds. Flower/leaf tea for colds and fever. Stems in sweat bath.",
            "cautions": "May cause allergic reactions in sensitive individuals. Avoid during pregnancy.",
            "verified": True,
            "source_author": "Garibaldi, Ann; Schofield, Janice J.",
            "source_url": "https://www.nps.gov/articles/ethnobotany-of-southeast-alaska.htm"
        },
        {
            "latin_binomial": "Petasites frigidus",
            "english_name": "Coltsfoot / Sweet Coltsfoot",
            "native_alaskan_name": "Saxsit (Yupik); Nuuqpak (Inupiaq)",
            "native_language": "Yupik, Inupiaq",
            "family": "Asteraceae",
            "description": "Large-leaved perennial that appears before flowers bloom. Found in wet areas across Alaska. Important lung medicine.",
            "habitat": "Streambanks, wet meadows, seeps, shorelines",
            "traditional_uses": "Traditional cough and lung medicine. Leaves used for respiratory complaints, bronchitis, and asthma. One of the most important respiratory medicines.",
            "parts_used": "Leaves, roots",
            "preparation": "Leaves dried and steeped as tea for coughs. Root decoction stronger. Often combined with Labrador tea.",
            "cautions": "Contains pyrrolizidine alkaloids; use only short-term. Not for long-term daily use.",
            "verified": True,
            "source_author": "Jones, Anore; Kari, Priscilla Russell",
            "source_url": "https://www.fs.usda.gov/Internet/FSE_DOCUMENTS/stelprdb5202434.pdf"
        },
        {
            "latin_binomial": "Epilobium angustifolium",
            "english_name": "Fireweed",
            "native_alaskan_name": "Cama'i (Dena'ina); Pamiuqtaq (Yupik)",
            "native_language": "Dena'ina, Yupik",
            "family": "Onagraceae",
            "description": "Tall showy perennial with pink-purple flowers, famous for colonizing burned areas. Alaska's official flower. Important food and medicine plant.",
            "habitat": "Burned areas, roadsides, meadows, open forests, riverbanks",
            "traditional_uses": "Young shoots eaten as greens. Flowers used for honey/tea. Leaves used for intestinal complaints. Pith used for burns and skin irritations. One of the most versatile plants.",
            "parts_used": "Young shoots, leaves, flowers, pith (inner stem)",
            "preparation": "Shoots peeled and eaten raw or cooked. Flower/leaf tea for digestion. Pith applied to burns.",
            "cautions": "None known. Very safe food plant.",
            "verified": True,
            "source_author": "Kari, Priscilla Russell; Jones, Anore; Schofield, Janice J.",
            "source_url": "https://www.uaf.edu/ces/"
        },
        {
            "latin_binomial": "Sambucus racemosa",
            "english_name": "Red Elderberry",
            "native_alaskan_name": "Haawak (Tlingit); Tl'eek (Haida)",
            "native_language": "Tlingit, Haida",
            "family": "Adoxaceae",
            "description": "Large shrub with compound leaves and clusters of bright red berries. Found in Southeast Alaska coastal forests.",
            "habitat": "Coastal temperate rainforest, streambanks, forest openings",
            "traditional_uses": "Berries cooked and used for food. Bark used medicinally. Important food source but requires proper preparation.",
            "parts_used": "Berries (cooked only), bark",
            "preparation": "Berries must be cooked before eating. Used in jams, jellies. Bark tea used for various ailments.",
            "cautions": "RAW BERRIES ARE TOXIC. Must be cooked thoroughly. Contains cyanogenic compounds when raw. Seeds should be strained out.",
            "verified": True,
            "source_author": "Garibaldi, Ann; Kari, Priscilla Russell",
            "source_url": "https://www.nps.gov/articles/ethnobotany-of-southeast-alaska.htm"
        },
        {
            "latin_binomial": "Heracleum lanatum",
            "english_name": "Cow Parsnip / Pushki",
            "native_alaskan_name": "Ggwsdaa (Tlingit); Ggwsda (Haida)",
            "native_language": "Tlingit, Haida",
            "family": "Apiaceae",
            "description": "Very large perennial with huge leaves and white flower umbels. One of the most important traditional vegetables in Southeast Alaska.",
            "habitat": "Coastal meadows, streambanks, open forests, roadsides",
            "traditional_uses": "Young stems and leaf stalks peeled and eaten. Important spring vegetable. Used as famine food. Stems used for making fish traps.",
            "parts_used": "Young stems, leaf stalks (peeled), roots",
            "preparation": "Peel outer skin and eat stems/stalks raw, steamed, or boiled. Must peel completely - outer skin contains phototoxic compounds.",
            "cautions": "SKIN CONTACT WITH SAP + SUN = SEVERE BLISTERS (phytophotodermatitis). Always peel completely. Wear gloves when harvesting.",
            "verified": True,
            "source_author": "Jones, Anore; Kari, Priscilla Russell",
            "source_url": "https://www.uaf.edu/ces/"
        },
        {
            "latin_binomial": "Plantago major",
            "english_name": "Broadleaf Plantain",
            "native_alaskan_name": "Various local names",
            "native_language": "Multiple Alaska Native languages",
            "family": "Plantaginaceae",
            "description": "Low-growing perennial with broad oval leaves and seed spikes. Common worldwide and widely adopted by Alaska Natives post-contact.",
            "habitat": "Disturbed areas, roadsides, beaches, lawns",
            "traditional_uses": "Poultice for insect bites, wounds, and skin irritations. Leaf tea for coughs and digestive issues. Seeds as laxative.",
            "parts_used": "Leaves, seeds",
            "preparation": "Crushed leaf poultice for bites and wounds. Leaf tea for respiratory and digestive complaints.",
            "cautions": "None known. Very safe.",
            "verified": True,
            "source_author": "Garibaldi, Ann",
            "source_url": "https://www.fs.usda.gov/Internet/FSE_DOCUMENTS/stelprdb5202434.pdf"
        },
        {
            "latin_binomial": "Urtica dioica",
            "english_name": "Stinging Nettle",
            "native_alaskan_name": "Local names vary by region",
            "native_language": "Multiple",
            "family": "Urticaceae",
            "description": "Tall perennial with stinging hairs on leaves and stems. Found in rich soils near human habitation across Alaska.",
            "habitat": "Rich soils, areas with past human occupation, streambanks, forest edges",
            "traditional_uses": "Highly nutritious spring green. Leaf tea for allergies, anemia, and general tonic. Used in steam baths. Fibers used for cordage.",
            "parts_used": "Young shoots, leaves, stems",
            "preparation": "Young shoots boiled/steamed (cooking neutralizes sting). Dried leaf tea. Fibers stripped for cordage.",
            "cautions": "Raw plant stings. Cooking or drying neutralizes. Do not touch with bare skin when fresh.",
            "verified": True,
            "source_author": "Schofield, Janice J.; Jones, Anore",
            "source_url": "https://www.uaf.edu/ces/"
        },
        {
            "latin_binomial": "Alnus viridis ssp. crispa",
            "english_name": "Green Alder / Mountain Alder",
            "native_alaskan_name": "Gizi (Dena'ina); Ts'i (Ahtna)",
            "native_language": "Dena'ina, Ahtna",
            "family": "Betulaceae",
            "description": "Shrub or small tree with serrated leaves and catkins. Important medicine and dye plant across Interior Alaska.",
            "habitat": "Streambanks, wet slopes, avalanche chutes, forest edges",
            "traditional_uses": "Inner bark used for medicine and dye. Bark tea for skin conditions, tuberculosis symptoms, and as eyewash. Bark yields red-orange dye.",
            "parts_used": "Inner bark, catkins",
            "preparation": "Inner bark peeled and dried for tea. Fresh bark for dye. Sometimes combined with willow bark.",
            "cautions": "None known in traditional preparation amounts.",
            "verified": True,
            "source_author": "Kari, Priscilla Russell",
            "source_url": "https://www.uaf.edu/ces/"
        },
        {
            "latin_binomial": "Salix alaxensis",
            "english_name": "Feltleaf Willow",
            "native_alaskan_name": "Ggas (Dena'ina); Qanemciaq (Yupik)",
            "native_language": "Dena'ina, Yupik",
            "family": "Salicaceae",
            "description": "Tall shrub or small tree with large velvety leaves. Most important willow species for medicine in Alaska.",
            "habitat": "Riverbanks, floodplains, disturbed areas, south-facing slopes",
            "traditional_uses": "Inner bark used like aspirin for pain, fever, and inflammation. Leaf tea for digestive issues. Twigs used for basketry. Most widely used pain medicine in traditional Alaska.",
            "parts_used": "Inner bark, leaves, twigs",
            "preparation": "Inner bark peeled and steeped for headache, fever, pain. Leaf tea milder. Bark harvested in spring when sap flows.",
            "cautions": "Contains salicin (aspirin-like). Avoid if allergic to aspirin. May interact with blood thinners.",
            "verified": True,
            "source_author": "Garibaldi, Ann; Kari, Priscilla Russell",
            "source_url": "https://www.fs.usda.gov/Internet/FSE_DOCUMENTS/stelprdb5202434.pdf"
        },
        {
            "latin_binomial": "Arnica latifolia",
            "english_name": "Mountain Arnica",
            "native_alaskan_name": "Local names vary",
            "native_language": "Various Interior languages",
            "family": "Asteraceae",
            "description": "Perennial herb with yellow daisy-like flowers. Found in alpine meadows across Alaska.",
            "habitat": "Alpine meadows, subalpine slopes, open forests",
            "traditional_uses": "Topical use for bruises, sprains, muscle pain, and inflammation. Important external medicine. NOT for internal use.",
            "parts_used": "Flowers, leaves",
            "preparation": "Flower poultice or infused oil for external use only. Soak in oil for muscle rub.",
            "cautions": "TOXIC IF SWALLOWED. External use only. Do not apply to broken skin. Can cause contact dermatitis in sensitive individuals.",
            "verified": True,
            "source_author": "Garibaldi, Ann; Schofield, Janice J.",
            "source_url": "https://www.uaf.edu/ces/"
        },
        {
            "latin_binomial": "Matricaria discoidea",
            "english_name": "Pineapple Weed / Wild Chamomile",
            "native_alaskan_name": "Various local names",
            "native_language": "Multiple",
            "family": "Asteraceae",
            "description": "Low-growing annual with finely divided leaves and small yellow-green cone-shaped flower heads. Smells like pineapple when crushed. Introduced but widely adopted.",
            "habitat": "Disturbed areas, roadsides, compacted soils, near human habitation",
            "traditional_uses": "Tea for stomach upset, colic, menstrual cramps, and to promote sleep. Gentle children's medicine. Very safe.",
            "parts_used": "Flowers, leaves",
            "preparation": "Flower heads steeped as tea. Very mild - safe for children.",
            "cautions": "None known. Very safe. Rare ragweed allergy.",
            "verified": True,
            "source_author": "Schofield, Janice J.",
            "source_url": "https://www.uaf.edu/ces/"
        },
        {
            "latin_binomial": "Equisetum arvense",
            "english_name": "Horsetail / Scouring Rush",
            "native_alaskan_name": "Local names vary by region",
            "native_language": "Multiple Interior languages",
            "family": "Equisetaceae",
            "description": "Primitive vascular plant with jointed hollow stems and whorls of thin branches. Found in wet areas across Alaska.",
            "habitat": "Wet meadows, streambanks, disturbed wet areas",
            "traditional_uses": "Stem tea for kidney and bladder complaints. High silica content makes it useful as scouring pad. External wash for wounds.",
            "parts_used": "Stems (above-ground parts)",
            "preparation": "Dried stem tea for urinary system. Fresh stems used to scrub pots.",
            "cautions": "Contains thiaminase - may deplete vitamin B1 with long-term heavy use. Use in moderation. Not for long-term daily use.",
            "verified": True,
            "source_author": "Garibaldi, Ann",
            "source_url": "https://www.fs.usda.gov/Internet/FSE_DOCUMENTS/stelprdb5202434.pdf"
        },
        {
            "latin_binomial": "Valeriana sitchensis",
            "english_name": "Sitka Valerian / Tobacco Root",
            "native_alaskan_name": "Local names",
            "native_language": "Various Southeast and Southcentral languages",
            "family": "Caprifoliaceae",
            "description": "Perennial herb with clusters of small white-pink flowers and strong-smelling roots. Found in moist mountain meadows.",
            "habitat": "Moist meadows, subalpine areas, streambanks",
            "traditional_uses": "Root used as sedative, sleep aid, and muscle relaxant. Important medicine for anxiety and insomnia. Used in steam baths.",
            "parts_used": "Roots",
            "preparation": "Root decoction (strong tea) for sleep and anxiety. Dried root has strong odor. Used in sweat baths.",
            "cautions": "May cause drowsiness. Do not combine with alcohol or sedatives. Can cause vivid dreams. Strong odor.",
            "verified": True,
            "source_author": "Garibaldi, Ann; Kari, Priscilla Russell",
            "source_url": "https://www.uaf.edu/ces/"
        },
        {
            "latin_binomial": "Menyanthes trifoliata",
            "english_name": "Buckbean / Bogbean",
            "native_alaskan_name": "Various local names",
            "native_language": "Multiple Interior languages",
            "family": "Menyanthaceae",
            "description": "Perennial aquatic plant with trifoliate leaves and white fringed flowers. Found in bogs and shallow water.",
            "habitat": "Bogs, shallow ponds, wet meadows, margins of lakes",
            "traditional_uses": "Bitter digestive tonic. Leaf tea for appetite, digestion, and rheumatism. Used as famine food in some areas.",
            "parts_used": "Leaves, roots",
            "preparation": "Leaf tea as bitter tonic. Must be dried before use.",
            "cautions": "Very bitter. May cause digestive upset in large amounts. Use in moderation.",
            "verified": True,
            "source_author": "Garibaldi, Ann",
            "source_url": "https://www.fs.usda.gov/Internet/FSE_DOCUMENTS/stelprdb5202434.pdf"
        },

        # --- ROOT/TUBER PLANTS ---
        {
            "latin_binomial": "Hedysarum alpinum",
            "english_name": "Alpine Sweetvetch / Eskimo Potato",
            "native_alaskan_name": "Maqpiq (Yupik); Masru (Inupiaq)",
            "native_language": "Yupik, Inupiaq",
            "family": "Fabaceae",
            "description": "Perennial herb with pea-like flowers and thick edible roots. One of the most important traditional root foods in Arctic Alaska.",
            "habitat": "Dry tundra slopes, gravelly riverbanks, south-facing slopes",
            "traditional_uses": "Roots are a major carbohydrate source. Eaten raw, boiled, or preserved in seal oil. Critical subsistence food.",
            "parts_used": "Roots",
            "preparation": "Roots dug in fall, peeled, and eaten raw or boiled. Can be stored in seal oil.",
            "cautions": "None known. Important food plant.",
            "verified": True,
            "source_author": "Jones, Anore; Kari, Priscilla Russell",
            "source_url": "https://www.uaf.edu/ces/"
        },
        {
            "latin_binomial": "Claytonia tuberosa",
            "english_name": "Siberian Springbeauty / Eskimo Potato",
            "native_alaskan_name": "Various local names",
            "native_language": "Multiple Interior and Arctic languages",
            "family": "Montiaceae",
            "description": "Small perennial with succulent leaves and small pink flowers. Has round edible corms.",
            "habitat": "Tundra, rocky slopes, alpine meadows",
            "traditional_uses": "Corm eaten as food. Important spring food source when other stores are low.",
            "parts_used": "Corms (underground stems)",
            "preparation": "Eaten raw or cooked. Small but nutritious.",
            "cautions": "None known.",
            "verified": True,
            "source_author": "Jones, Anore",
            "source_url": "https://www.uaf.edu/ces/"
        },

        # --- TREES (MEDICINAL/Food) ---
        {
            "latin_binomial": "Picea glauca",
            "english_name": "White Spruce",
            "native_alaskan_name": "Ts'et (Dena'ina); Cikuvi (Yupik)",
            "native_language": "Dena'ina, Yupik",
            "family": "Pinaceae",
            "description": "Tall coniferous tree with needle-like leaves and woody cones. The most widespread tree in Alaska.",
            "habitat": "Boreal forest, river valleys, well-drained slopes",
            "traditional_uses": "Inner bark eaten as famine food. Needles for vitamin C tea. Pitch used for wounds and skin conditions. Boughs used in sweat baths. Wood for construction and tools.",
            "parts_used": "Inner bark, needles, pitch, boughs",
            "preparation": "Inner bark scraped and dried. Needle tea for scurvy prevention. Pitch applied to wounds.",
            "cautions": "None known. Very safe.",
            "verified": True,
            "source_author": "Kari, Priscilla Russell; Jones, Anore",
            "source_url": "https://www.uaf.edu/ces/"
        },
        {
            "latin_binomial": "Populus balsamifera",
            "english_name": "Balsam Poplar / Cottonwood",
            "native_alaskan_name": "K'el (Dena'ina); K'el (Ahtna)",
            "native_language": "Dena'ina, Ahtna",
            "family": "Salicaceae",
            "description": "Large deciduous tree with resinous buds and triangular leaves. Found along rivers in Interior Alaska.",
            "habitat": "River floodplains, gravel bars, disturbed areas",
            "traditional_uses": "Buds steeped for tea for coughs, colds, and sore throats. Resin used as antimicrobial salve. Inner bark for food. Important medicine tree.",
            "parts_used": "Buds, resin, inner bark",
            "preparation": "Winter bud tea for respiratory infections. Resin collected and applied to cuts. Bark eaten as emergency food.",
            "cautions": "None known. Very safe.",
            "verified": True,
            "source_author": "Garibaldi, Ann; Kari, Priscilla Russell",
            "source_url": "https://www.fs.usda.gov/Internet/FSE_DOCUMENTS/stelprdb5202434.pdf"
        },
        {
            "latin_binomial": "Betula papyrifera",
            "english_name": "Paper Birch",
            "native_alaskan_name": "Neyh (Dena'ina); Neyh (Ahtna); Ciisaq (Yupik)",
            "native_language": "Dena'ina, Ahtna, Yupik",
            "family": "Betulaceae",
            "description": "Medium-sized deciduous tree with white peeling bark. One of the most culturally important trees in Alaska.",
            "habitat": "Mixed forests, river valleys, burned areas, well-drained slopes",
            "traditional_uses": "Sap used as beverage and medicine. Inner bark eaten as food. Bark for baskets, canoes, and shelter. Leaves for tea. Anti-inflammatory properties.",
            "parts_used": "Sap, inner bark, leaves, bark",
            "preparation": "Sap collected in spring as sweet drink. Inner bark scraped and eaten. Leaf tea for inflammation.",
            "cautions": "None known. Very safe.",
            "verified": True,
            "source_author": "Jones, Anore; Kari, Priscilla Russell",
            "source_url": "https://www.uaf.edu/ces/"
        },

        # --- MUSHROOMS (included as culturally significant) ---
        {
            "latin_binomial": "Fomes fomentarius",
            "english_name": "Tinder Fungus / Amadou",
            "native_alaskan_name": "Various local names",
            "native_language": "Multiple",
            "family": "Polyporaceae",
            "description": "Hard woody bracket fungus growing on birch trees. Used for fire-starting and medicinal purposes.",
            "habitat": "On dead or dying birch trees",
            "traditional_uses": "Used as tinder for fire-starting. Pounded and used as styptic to stop bleeding. Medicinal tea for various ailments.",
            "parts_used": "Fruiting body (bracket)",
            "preparation": "Dried and pounded for tinder. Powder used on wounds to stop bleeding.",
            "cautions": "None known. Not edible.",
            "verified": True,
            "source_author": "Jones, Anore",
            "source_url": "https://www.uaf.edu/ces/"
        },
        {
            "latin_binomial": "Inonotus obliquus",
            "english_name": "Chaga",
            "native_alaskan_name": "Various local names",
            "native_language": "Multiple Interior languages",
            "family": "Hymenochaetaceae",
            "description": "Black irregular conk growing on birch trees. Hard, crusty exterior with orange-brown interior. Important traditional medicine.",
            "habitat": "On living birch trees, especially older trees",
            "traditional_uses": "Tea used for immune support, stomach complaints, and general wellness. Highly regarded tonic medicine. Modern research confirms antioxidant properties.",
            "parts_used": "Conk (inner portion)",
            "preparation": "Small pieces broken off and steeped as tea. Can be reused multiple times. Very bitter.",
            "cautions": "May interact with blood thinners. Use in moderation. Harvest sustainably - do not take entire conk.",
            "verified": True,
            "source_author": "Garibaldi, Ann",
            "source_url": "https://www.uaf.edu/ces/"
        },
        {
            "latin_binomial": "Arctostaphylos uva-ursi",
            "english_name": "Kinnikinnick / Bearberry",
            "native_alaskan_name": "Ggagga (Dena'ina); various local names",
            "native_language": "Dena'ina, multiple Interior languages",
            "family": "Ericaceae",
            "description": "Low evergreen trailing shrub with small leathery leaves, pink bell-shaped flowers, and red berries. One of the most culturally important plants in Interior Alaska.",
            "habitat": "Dry slopes, open forests, river bluffs, burned areas, well-drained sandy soils",
            "traditional_uses": "Leaves dried and mixed with tobacco as smoking mixture (kinnikinnick). Leaf tea for urinary tract infections and kidney problems. Berries eaten fresh or in akutaq. One of the most widely used medicinal plants across Alaska.",
            "parts_used": "Leaves, berries",
            "preparation": "Leaves dried slowly and mixed with tobacco for smoking. Leaf tea for urinary complaints. Berries fresh or preserved.",
            "cautions": "Large doses may cause stomach upset. Contains arbutin; prolonged use may stress kidneys. Safe in moderate amounts.",
            "verified": True,
            "source_author": "Kari, Priscilla Russell; Garibaldi, Ann",
            "source_url": "https://www.fs.usda.gov/Internet/FSE_DOCUMENTS/stelprdb5202434.pdf"
        },
        {
            "latin_binomial": "Lonicera caerulea var. edulis",
            "english_name": "Haskap / Blue-berried Honeysuckle / Sweetberry Honeysuckle",
            "native_alaskan_name": "Sgguya (Dena'ina); various Yupik names",
            "native_language": "Dena'ina, Yupik",
            "family": "Caprifoliaceae",
            "description": "Deciduous shrub with oval opposite leaves and tubular flowers yielding dark blue elongated berries. One of the earliest berries to ripen in Alaska.",
            "habitat": "Riverbanks, moist forests, thickets, forest edges",
            "traditional_uses": "Berries eaten fresh, dried, or preserved in seal oil. Early-season food source when other berries are not yet ripe. Important subsistence berry across Interior and western Alaska.",
            "parts_used": "Berries",
            "preparation": "Eaten fresh. Mixed with other berries in akutaq. Dried for winter storage.",
            "cautions": "None known. Very safe and nutritious.",
            "verified": True,
            "source_author": "Jones, Anore; Kari, Priscilla Russell",
            "source_url": "https://www.uaf.edu/ces/"
        },
        {
            "latin_binomial": "Rosa acicularis",
            "english_name": "Prickly Rose / Wild Rose",
            "native_alaskan_name": "K'enq'a (Dena'ina); various local names",
            "native_language": "Dena'ina, multiple Interior languages",
            "family": "Rosaceae",
            "description": "Deciduous shrub with prickly stems, compound leaves, and pink five-petaled flowers. Found across Alaska in open areas. Produces bright red rose hips in fall.",
            "habitat": "Open forests, roadsides, riverbanks, burned areas, meadows",
            "traditional_uses": "Rose hips are one of the best natural sources of vitamin C — critical for preventing scurvy during long winters. Hips eaten fresh, dried, or steeped as tea. Petals used for food and decoration.",
            "parts_used": "Fruits (hips), petals",
            "preparation": "Hips dried and stored for winter tea. Fresh hips mashed and steeped. Petals used in salads or as garnish.",
            "cautions": "Remove seeds from hips before eating — seeds have irritating hairs inside. Outer flesh only.",
            "verified": True,
            "source_author": "Schofield, Janice J.; Jones, Anore",
            "source_url": "https://www.uaf.edu/ces/"
        },
        {
            "latin_binomial": "Shepherdia canadensis",
            "english_name": "Soapberry / Soopolallie / Buffaloberry / Indian Ice Cream Berry",
            "native_alaskan_name": "Suts' (Dena'ina); Suts'a (Ahtna); Nauriat (Inupiaq)",
            "native_language": "Dena'ina, Ahtna, Inupiaq",
            "family": "Elaeagnaceae",
            "description": "Small deciduous shrub with silvery-scaly leaves and clusters of small orange-red translucent berries. One of the most fascinating traditional foods in Alaska.",
            "habitat": "Open forests, river terraces, south-facing slopes, burned areas",
            "traditional_uses": "Berries whipped with water, sugar, or seal oil into a frothy confection called 'Indian ice cream' or 'Eskimo ice cream.' One of the most unique Alaska Native foods. Also used medicinally.",
            "parts_used": "Berries",
            "preparation": "Berries whipped vigorously with water or oil until foamy and light. Traditionally done by hand or with special paddles.",
            "cautions": "Berries are extremely bitter when raw — must be whipped/frothed to be palatable. Very sour/bitter taste before preparation. Some people acquire the taste over time.",
            "verified": True,
            "source_author": "Jones, Anore; Kari, Priscilla Russell",
            "source_url": "https://www.uaf.edu/ces/"
        },
        {
            "latin_binomial": "Viburnum edule",
            "english_name": "Highbush Cranberry / Mooseberry / Squashberry",
            "native_alaskan_name": "Ben dena (Dena'ina); Paunnaq (Inupiaq); various",
            "native_language": "Dena'ina, Inupiaq",
            "family": "Adoxaceae",
            "description": "Tall shrub with opposite maple-like leaves, white flower clusters, and bright red translucent berries. Berries persist on the bush well into winter.",
            "habitat": "Moist forests, thickets, riverbanks, open woods",
            "traditional_uses": "Berries important food source that persists through winter. Eaten fresh, in akutaq, or preserved. Sometimes mixed with other berries. Bark used medicinally for cramps.",
            "parts_used": "Berries, bark",
            "preparation": "Berries eaten fresh or cooked. Often mixed with sugar because they are tart. Bark tea for menstrual cramps.",
            "cautions": "Berries have a strong 'wintergreen' or musty smell that some find unpleasant — this is normal and does not mean they are spoiled.",
            "verified": True,
            "source_author": "Garibaldi, Ann; Jones, Anore",
            "source_url": "https://www.uaf.edu/ces/"
        },
        {
            "latin_binomial": "Cornus canadensis",
            "english_name": "Bunchberry / Creeping Dogwood / Puddingberry",
            "native_alaskan_name": "Ch'elqani (Dena'ina); various local names",
            "native_language": "Dena'ina, multiple",
            "family": "Cornaceae",
            "description": "Low creeping perennial herb with whorled leaves and clusters of bright red berries atop a central stalk. Very common in Alaska forests.",
            "habitat": "Coniferous forests, mossy areas, shaded woodlands",
            "traditional_uses": "Berries eaten fresh — sweet and tasty but seedy. Often mixed with other berries. Young plants sometimes used as potherb.",
            "parts_used": "Berries",
            "preparation": "Eaten fresh. Mixed with other berries.",
            "cautions": "None known. Very safe. Large quantities may cause mild digestive upset due to seeds.",
            "verified": True,
            "source_author": "Jones, Anore; Schofield, Janice J.",
            "source_url": "https://www.uaf.edu/ces/"
        },
        {
            "latin_binomial": "Sorbus sitchensis",
            "english_name": "Sitka Mountain Ash / Pacific Mountain Ash",
            "native_alaskan_name": "Haawak (Tlingit); various Southeast names",
            "native_language": "Tlingit, Haida",
            "family": "Rosaceae",
            "description": "Small tree or large shrub with compound leaves, clusters of white flowers, and bright orange-red berries. Important food in Southeast Alaska.",
            "habitat": "Coastal forests, open woodlands, avalanche slopes, streambanks",
            "traditional_uses": "Berries eaten fresh or dried. Important late-season food source. Sometimes combined with fish eggs. Berries persist on tree into winter.",
            "parts_used": "Berries",
            "preparation": "Eaten fresh. Dried for winter. Sometimes cooked into preserves.",
            "cautions": "None known. Safe food plant.",
            "verified": True,
            "source_author": "Garibaldi, Ann; Kari, Priscilla Russell",
            "source_url": "https://www.nps.gov/articles/ethnobotany-of-southeast-alaska.htm"
        },
        {
            "latin_binomial": "Maianthemum stellatum",
            "english_name": "Star-flowered Solomon's Seal / Starry False Lily of the Valley",
            "native_alaskan_name": "Qełch'en (Dena'ina); various",
            "native_language": "Dena'ina",
            "family": "Asparagaceae",
            "description": "Perennial herb with arching stems, alternate leaves, and clusters of small white star-shaped flowers followed by green berries ripening to red. Found in moist areas across Alaska.",
            "habitat": "Moist forests, streambanks, meadows, thickets",
            "traditional_uses": "Young shoots gathered in spring and eaten like asparagus. Berries eaten in small quantities. Roots used medicinally for sore throats and as a poultice.",
            "parts_used": "Young shoots, berries, roots",
            "preparation": "Shoots collected when 4-6 inches tall, boiled briefly. Berries eaten fresh in small amounts.",
            "cautions": "Mature berries can have laxative effects in large quantities. Roots should not be consumed raw in large amounts.",
            "verified": True,
            "source_author": "Jones, Anore; Kari, Priscilla Russell",
            "source_url": "https://www.uaf.edu/ces/"
        },
        {
            "latin_binomial": "Streptopus amplexifolius",
            "english_name": "Clasping Twisted Stalk / Watermelon Berry",
            "native_alaskan_name": "Qełch'en (Dena'ina); similar names across Interior",
            "native_language": "Dena'ina",
            "family": "Liliaceae",
            "description": "Perennial herb with clasping leaves and small greenish-white bell-shaped flowers that dangle from twisted stalks, followed by oval translucent orange-red berries. Called 'watermelon berry' for its flavor.",
            "habitat": "Moist shady forests, streambanks, thickets",
            "traditional_uses": "Berries are sweet and juicy — eaten fresh by children. Young shoots also eaten. A favorite children's snack plant across Interior Alaska.",
            "parts_used": "Berries, young shoots",
            "preparation": "Berries eaten fresh off the stem. Young shoots boiled briefly.",
            "cautions": "None known. Very safe and popular with children.",
            "verified": True,
            "source_author": "Jones, Anore; Schofield, Janice J.",
            "source_url": "https://www.uaf.edu/ces/"
        },
        {
            "latin_binomial": "Oxyria digyna",
            "english_name": "Mountain Sorrel / Alpine Sorrel",
            "native_alaskan_name": "Various Arctic names; Inupiaq local names",
            "native_language": "Inupiaq, Yupik",
            "family": "Polygonaceae",
            "description": "Small perennial with rounded kidney-shaped leaves on long stalks and tiny greenish flowers in clusters. Found in alpine and Arctic areas. Leaves have a pleasant sour taste.",
            "habitat": "Alpine tundra, rocky slopes, gravel bars, disturbed ground in Arctic regions",
            "traditional_uses": "Leaves are an important fresh green in Arctic and alpine regions. Eaten raw as a salad green or trail nibble. One of the most important wild vegetables in the Arctic.",
            "parts_used": "Leaves",
            "preparation": "Eaten fresh. Adds a lemony/sour flavor to soups and stews. Can be dried for winter use.",
            "cautions": "High in oxalic acid — should not be consumed in extremely large quantities by people prone to kidney stones. Safe in normal food amounts.",
            "verified": True,
            "source_author": "Jones, Anore; Garibaldi, Ann",
            "source_url": "https://www.uaf.edu/ces/"
        },
        {
            "latin_binomial": "Mertensia maritima",
            "english_name": "Oysterplant / Sea Bluebells / Oysterleaf",
            "native_alaskan_name": "K'etl'el (Dena'ina); various coastal names",
            "native_language": "Dena'ina, various coastal languages",
            "family": "Boraginaceae",
            "description": "Low-growing coastal perennial with fleshy bluish-green spoon-shaped leaves and clusters of blue bell-shaped flowers. Grows on beaches and rocky shores. Leaves taste remarkably like oysters.",
            "habitat": "Coastal beaches, rocky shores, gravel bars, salt spray zones",
            "traditional_uses": "Leaves eaten raw as a vegetable — truly taste like oysters. Used fresh in salads or as a condiment. One of the most surprising wild foods in Alaska.",
            "parts_used": "Leaves",
            "preparation": "Eaten raw. Adds oyster flavor to salads and sandwiches. Best harvested before flowering.",
            "cautions": "None known. Very safe. Do not confuse with unrelated plants growing in the same habitat.",
            "verified": True,
            "source_author": "Jones, Anore; Schofield, Janice J.",
            "source_url": "https://www.uaf.edu/ces/"
        },
        {
            "latin_binomial": "Coptis trifolia",
            "english_name": "Goldthread / Canker Root / Yellowroot",
            "native_alaskan_name": "C'edesq' (Dena'ina); various Interior names",
            "native_language": "Dena'ina, Ahtna",
            "family": "Ranunculaceae",
            "description": "Small evergreen perennial with glossy divided leaves and bright yellow thread-like roots. Found in moist mossy forests across Alaska. The roots contain berberine, a bright yellow bitter compound.",
            "habitat": "Mossy forests, bogs, wet areas with sphagnum moss",
            "traditional_uses": "Roots used as a bitter digestive tonic, mouthwash for canker sores and sore throats, and as an antimicrobial wash for wounds. One of the most important medicinal plants in Interior Alaska.",
            "parts_used": "Roots",
            "preparation": "Small piece of root chewed for mouth sores or sore throat. Root steeped as bitter tea for digestive complaints. External wash for skin infections.",
            "cautions": "Very bitter. Contains berberine — do not use during pregnancy. Safe in traditional amounts for short-term use.",
            "verified": True,
            "source_author": "Garibaldi, Ann; Kari, Priscilla Russell",
            "source_url": "https://www.fs.usda.gov/Internet/FSE_DOCUMENTS/stelprdb5202434.pdf"
        },
        {
            "latin_binomial": "Anemone narcissiflora",
            "english_name": "Narcissus-flowered Anemone / Northern Anemone",
            "native_alaskan_name": "Various local names across Interior",
            "native_language": "Dena'ina, Ahtna",
            "family": "Ranunculaceae",
            "description": "Perennial herb with deeply divided leaves and clusters of white petal-like sepals surrounding a central button of stamens. Found in meadows and open areas across Alaska.",
            "habitat": "Alpine meadows, open tundra, moist meadows, forest openings",
            "traditional_uses": "Used medicinally for various conditions including lung complaints and as a general tonic. Root used for digestive issues. Some groups used it for heart medicine.",
            "parts_used": "Roots, leaves",
            "preparation": "Root tea for digestive and respiratory complaints. External poultice for sores.",
            "cautions": "All Ranunculaceae plants contain irritating compounds. Do not consume in large quantities. External use is safer than internal.",
            "verified": True,
            "source_author": "Garibaldi, Ann",
            "source_url": "https://www.fs.usda.gov/Internet/FSE_DOCUMENTS/stelprdb5202434.pdf"
        },
        {
            "latin_binomial": "Pedicularis labradorica",
            "english_name": "Labrador Lousewort",
            "native_alaskan_name": "Various local names",
            "native_language": "Multiple Interior languages",
            "family": "Orobanchaceae",
            "description": "Perennial herb with fern-like leaves and spikes of yellow or purple flowers. Semi-parasitic on other plants' roots. Found in wet meadows and along streams.",
            "habitat": "Wet meadows, streambanks, tundra, moist slopes",
            "traditional_uses": "Root tea used for general weakness, as a blood tonic, and for muscle and nerve pain. Important general tonic medicine across Interior Alaska.",
            "parts_used": "Roots",
            "preparation": "Root decoction (strong tea) for pain and weakness. Sometimes combined with other tonic plants.",
            "cautions": "Contains various compounds — use in traditional amounts. Not for long-term daily use.",
            "verified": True,
            "source_author": "Garibaldi, Ann; Kari, Priscilla Russell",
            "source_url": "https://www.uaf.edu/ces/"
        },
        {
            "latin_binomial": "Castilleja miniata",
            "english_name": "Great Red Paintbrush / Indian Paintbrush / Prairie Fire",
            "native_alaskan_name": "Various Interior and Southcentral names",
            "native_language": "Multiple",
            "family": "Orobanchaceae",
            "description": "Showy perennial herb with bright red-orange leaf-like bracts surrounding small greenish flowers. Semi-parasitic on grass roots. Very conspicuous in meadows.",
            "habitat": "Meadows, open slopes, streambanks, forest edges",
            "traditional_uses": "Whole plant used as hair wash to promote hair growth and darken hair color. Leaf tea for sore throats. Used as a dye plant.",
            "parts_used": "Whole plant, leaves",
            "preparation": "Plant steeped as hair rinse. Leaf tea gargled for sore throat.",
            "cautions": "Some paintbrush species can concentrate selenium from soil. Use from known safe locations.",
            "verified": True,
            "source_author": "Garibaldi, Ann; Schofield, Janice J.",
            "source_url": "https://www.uaf.edu/ces/"
        },
        {
            "latin_binomial": "Geum triflorum",
            "english_name": "Prairie Smoke / Old Man's Whiskers / Three-flowered Avens",
            "native_alaskan_name": "C'elggwde (Dena'ina); various",
            "native_language": "Dena'ina",
            "family": "Rosaceae",
            "description": "Perennial herb with divided leaves and nodding clusters of three pinkish-purple flowers that develop into fluffy plumed seed heads. One of the most distinctive plants in Alaska meadows.",
            "habitat": "Dry meadows, open slopes, forest edges, tundra",
            "traditional_uses": "Root tea used for digestive complaints, sore throats, and as a general tonic. Seeds have a clove-like aroma. Some groups used root for heart medicine.",
            "parts_used": "Roots",
            "preparation": "Root tea for digestive and respiratory complaints. Harvested in fall when roots are most potent.",
            "cautions": "Safe in traditional amounts. Very astringent.",
            "verified": True,
            "source_author": "Garibaldi, Ann; Kari, Priscilla Russell",
            "source_url": "https://www.uaf.edu/ces/"
        },
        {
            "latin_binomial": "Potentilla anserina",
            "english_name": "Silverweed / Goose Grass / Wild Tansy",
            "native_alaskan_name": "Various local names across Alaska",
            "native_language": "Multiple",
            "family": "Rosaceae",
            "description": "Low-growing perennial with silvery-haired pinnate leaves and small yellow five-petaled flowers. Found in sandy or disturbed soils near coasts and rivers.",
            "habitat": "Sandy beaches, riverbanks, roadsides, disturbed areas, coastal meadows",
            "traditional_uses": "Roots were an important starchy food source — roasted or boiled like potatoes. Leaf tea used for digestive complaints and as a general tonic. Important emergency food.",
            "parts_used": "Roots, leaves",
            "preparation": "Roots dug in fall, cleaned, and boiled or roasted. Tastes somewhat like parsnip or potato. Leaf tea for digestion.",
            "cautions": "None known. Very safe food and medicine plant.",
            "verified": True,
            "source_author": "Jones, Anore; Schofield, Janice J.",
            "source_url": "https://www.uaf.edu/ces/"
        },
        {
            "latin_binomial": "Lupinus arcticus",
            "english_name": "Arctic Lupine",
            "native_alaskan_name": "Gguy (Dena'ina); various Yupik names",
            "native_language": "Dena'ina, Yupik",
            "family": "Fabaceae",
            "description": "Tall perennial with palmately compound leaves and showy spikes of blue to purple pea-like flowers. One of the most beautiful and widespread wildflowers in Alaska.",
            "habitat": "Meadows, roadsides, open forests, riverbanks, gravel bars",
            "traditional_uses": "Seeds were an important food source after proper leaching to remove alkaloids. Leaves used as a compress for inflammation. Very important food plant historically.",
            "parts_used": "Seeds (leached), leaves",
            "preparation": "Seeds soaked and leached in running water for several days to remove bitter alkaloids, then boiled or roasted. IMPORTANT: Raw seeds are toxic and must be leached.",
            "cautions": "RAW SEEDS ARE TOXIC. Must be thoroughly leached in running water for several days before eating. Do not eat flowers, leaves, or unprocessed seeds. The plant contains toxic alkaloids that are removed by leaching.",
            "verified": True,
            "source_author": "Jones, Anore; Kari, Priscilla Russell",
            "source_url": "https://www.uaf.edu/ces/"
        },
        {
            "latin_binomial": "Mertensia paniculata",
            "english_name": "Tall Bluebells / Northern Bluebells / Lungwort",
            "native_alaskan_name": "Various Interior names",
            "native_language": "Multiple Interior languages",
            "family": "Boraginaceae",
            "description": "Tall perennial herb with large ovate leaves and drooping clusters of blue-purple bell-shaped flowers. Very common in Alaska's boreal forest.",
            "habitat": "Moist forests, streambanks, thickets, burned areas",
            "traditional_uses": "Root tea used for respiratory complaints, tuberculosis symptoms, and as a general tonic. Called 'lungwort' for its traditional use for lung conditions.",
            "parts_used": "Roots, leaves",
            "preparation": "Root decoction for respiratory complaints. Leaf tea milder.",
            "cautions": "Contains pyrrolizidine alkaloids — use only short-term. Not for long-term daily use. Not for use during pregnancy.",
            "verified": True,
            "source_author": "Garibaldi, Ann",
            "source_url": "https://www.fs.usda.gov/Internet/FSE_DOCUMENTS/stelprdb5202434.pdf"
        },
        {
            "latin_binomial": "Linnaea borealis",
            "english_name": "Twinflower / Linnaeus's Flower",
            "native_alaskan_name": "Various local names; named for Carl Linnaeus",
            "native_language": "Multiple",
            "family": "Caprifoliaceae",
            "description": "Low creeping evergreen subshrub with paired round leaves and delicate pairs of pink bell-shaped flowers on thin upright stems. Carl Linnaeus considered this his favorite plant and named it after himself.",
            "habitat": "Mossy forests, shaded woodlands, boreal forest understory",
            "traditional_uses": "Used as a gentle sedative and for women's health. Leaf tea for insomnia and nervous conditions. Considered a gentle children's medicine in some traditions.",
            "parts_used": "Leaves, stems",
            "preparation": "Leaf tea for sleep and nervous complaints. Very mild.",
            "cautions": "None known. Very safe and gentle.",
            "verified": True,
            "source_author": "Schofield, Janice J.",
            "source_url": "https://www.uaf.edu/ces/"
        },
        {
            "latin_binomial": "Fragaria vesca",
            "english_name": "Wild Strawberry / Woodland Strawberry / Alpine Strawberry",
            "native_alaskan_name": "K'el sułt'ani (Dena'ina); various local names",
            "native_language": "Dena'ina, multiple",
            "family": "Rosaceae",
            "description": "Low perennial herb with trifoliate leaves, white five-petaled flowers, and small but intensely fragrant and flavorful red strawberries. Found in open woods and meadows.",
            "habitat": "Open forests, meadows, clearings, burned areas, roadsides",
            "traditional_uses": "Berries are small but packed with flavor — considered by many to taste better than cultivated strawberries. Eaten fresh, in akutaq, or dried. Leaves used for tea.",
            "parts_used": "Berries, leaves",
            "preparation": "Berries eaten fresh — often children compete to find them before birds do. Leaf tea as gentle digestive tonic.",
            "cautions": "None known. Very safe and delicious.",
            "verified": True,
            "source_author": "Jones, Anore; Schofield, Janice J.",
            "source_url": "https://www.uaf.edu/ces/"
        },
    
        # === Berries from Wikipedia SE Alaska list (with Tlingit names) ===
        {
            "latin_binomial": "Rubus spectabilis",
            "english_name": "Salmonberry",
            "native_alaskan_name": "Was'x'aan Tléigu (Tlingit)",
            "native_language": "Tlingit",
            "family": "Rosaceae",
            "description": "Species of bramble native to the west coast of North America. Fruit is typically yellow-orange or red, resembling raspberries. Both the fruit and other parts of the plant are edible. One of the most important berries in Southeast Alaska.",
            "habitat": "Coastal forests, streambanks, moist clearings, temperate rainforest (Tongass National Forest)",
            "traditional_uses": "Berries eaten raw, used in jams and jellies. One of the earliest berries to ripen in Southeast Alaska. Young shoots can be eaten raw or cooked in early spring.",
            "parts_used": "Berries, young shoots",
            "preparation": "Berries eaten raw or made into jam. Young shoots peeled and eaten raw or lightly cooked in spring.",
            "cautions": "None known. Very safe and important food plant.",
            "verified": True,
            "source_author": "Wikipedia / Telander, Todd (2012) / Olson, Wallace M. (1997)",
            "source_url": "https://en.wikipedia.org/wiki/List_of_edible_plants_and_mushrooms_of_southeast_Alaska"
        },
        {
            "latin_binomial": "Rubus arcticus",
            "english_name": "Nagoonberry / Arctic Raspberry",
            "native_alaskan_name": "Neigóon (Tlingit)",
            "native_language": "Tlingit, Inupiaq, Yupik",
            "family": "Rosaceae",
            "description": "Small perennial herb with trailing stems, compound leaves, and deep red-purple berries. One of the most prized berries in Alaska — sweet, aromatic, and delicate.",
            "habitat": "Damp low meadows, wet tundra, bogs, coastal meadows",
            "traditional_uses": "Berries eaten raw, used to make juice and tea. Highly prized but rare — not normally found in abundance. One of the most sought-after berries in Alaska.",
            "parts_used": "Berries",
            "preparation": "Eaten raw. Made into juice and tea. Too rare and fragile to preserve in large quantities.",
            "cautions": "Berries are very fragile. None known toxicity.",
            "verified": True,
            "source_author": "Wikipedia / Telander, Todd (2012)",
            "source_url": "https://en.wikipedia.org/wiki/List_of_edible_plants_and_mushrooms_of_southeast_Alaska"
        },
        {
            "latin_binomial": "Rubus parviflorus",
            "english_name": "Thimbleberry",
            "native_alaskan_name": "Ch'eex' (Tlingit)",
            "native_language": "Tlingit",
            "family": "Rosaceae",
            "description": "Deciduous shrub with large soft maple-like leaves and white flowers. Produces red, dome-shaped, hollow berries that look like thimbles. Very similar to the common raspberry but softer and sweeter.",
            "habitat": "Open forests, roadsides, disturbed areas, forest edges in Southeast Alaska",
            "traditional_uses": "Berries eaten raw, used in jams and jellies. Young shoots can be eaten raw or cooked. One of the most versatile wild berries in Southeast Alaska.",
            "parts_used": "Berries, young shoots",
            "preparation": "Berries eaten raw or made into jam. Shoots collected in spring and eaten raw or lightly cooked.",
            "cautions": "None known. Very safe.",
            "verified": True,
            "source_author": "Wikipedia / Telander, Todd (2012)",
            "source_url": "https://en.wikipedia.org/wiki/List_of_edible_plants_and_mushrooms_of_southeast_Alaska"
        },
        {
            "latin_binomial": "Vaccinium ovalifolium",
            "english_name": "Alaskan Blueberry / Early Blueberry",
            "native_alaskan_name": "Kanat'a (Tlingit)",
            "native_language": "Tlingit, multiple",
            "family": "Ericaceae",
            "description": "Deciduous shrub with oval leaves and clusters of blue-black berries. One of the most abundant and important berries in Southeast Alaska's temperate rainforest.",
            "habitat": "Wet sunny hillsides, forest openings, muskegs, Southeast Alaska temperate rainforest",
            "traditional_uses": "Berries eaten fresh and commonly used in jams, jellies, and baked goods. One of the most important subsistence berries in Southeast Alaska. Preserved for winter use.",
            "parts_used": "Berries",
            "preparation": "Eaten fresh, made into jam, jelly, and baked goods. Dried or frozen for winter.",
            "cautions": "None known. Very safe.",
            "verified": True,
            "source_author": "Wikipedia / Telander, Todd (2012)",
            "source_url": "https://en.wikipedia.org/wiki/List_of_edible_plants_and_mushrooms_of_southeast_Alaska"
        },
        {
            "latin_binomial": "Vaccinium vitis-idaea",
            "english_name": "Lowbush Cranberry / Lingonberry",
            "native_alaskan_name": "Dáxw (Tlingit)",
            "native_language": "Tlingit, Inupiaq, Yupik",
            "family": "Ericaceae",
            "description": "Low evergreen shrub with small leathery leaves and bright red berries. Found across Alaska. One of the most important winter berries because they persist on the plant.",
            "habitat": "Forests, tundra, muskegs, open areas across Alaska",
            "traditional_uses": "Berries eaten raw, commonly used in jams and jellies. In season late in the fall — one of the last berries available. Rich in antioxidants. Important winter food across all Alaska Native groups.",
            "parts_used": "Berries",
            "preparation": "Eaten raw, made into jam and jelly. Preserved for winter. Often picked after frost for best flavor.",
            "cautions": "None known. Very safe. One of the most important berries in Alaska.",
            "verified": True,
            "source_author": "Wikipedia / Telander, Todd (2012)",
            "source_url": "https://en.wikipedia.org/wiki/List_of_edible_plants_and_mushrooms_of_southeast_Alaska"
        },
        {
            "latin_binomial": "Fragaria chiloensis",
            "english_name": "Wild Strawberry / Beach Strawberry / Coast Strawberry",
            "native_alaskan_name": "Saákw (Tlingit)",
            "native_language": "Tlingit",
            "family": "Rosaceae",
            "description": "Low perennial herb with trifoliate leaves, white flowers, and small but intensely flavored red strawberries. Found in coastal areas of Southeast Alaska.",
            "habitat": "Coastal meadows, beaches, forest edges, openings in Southeast Alaska",
            "traditional_uses": "Berries eaten raw, used in jams and jellies. Leaves mashed to make tea. Fruits late in spring — one of the first berries available.",
            "parts_used": "Berries, leaves",
            "preparation": "Berries eaten raw or made into jam. Leaves mashed and steeped for tea.",
            "cautions": "None known. Very safe.",
            "verified": True,
            "source_author": "Wikipedia / Telander, Todd (2012)",
            "source_url": "https://en.wikipedia.org/wiki/List_of_edible_plants_and_mushrooms_of_southeast_Alaska"
        },
        {
            "latin_binomial": "Gaylussacia sp.",
            "english_name": "Huckleberry",
            "native_alaskan_name": "Tleikatánk (Tlingit)",
            "native_language": "Tlingit",
            "family": "Ericaceae",
            "description": "Shrub with small leathery leaves and dark blue-black berries. Found on sunny hillsides in Southeast Alaska. Similar to blueberries but with different flavor.",
            "habitat": "Sunny hillsides, open forests, Southeast Alaska",
            "traditional_uses": "Berries eaten raw, used in jams and jellies. An important late-summer berry in Southeast Alaska.",
            "parts_used": "Berries",
            "preparation": "Eaten raw or made into jam and jelly.",
            "cautions": "Worms frequently present among berries — inspect before eating. Otherwise safe.",
            "verified": True,
            "source_author": "Wikipedia / Telander, Todd (2012)",
            "source_url": "https://en.wikipedia.org/wiki/List_of_edible_plants_and_mushrooms_of_southeast_Alaska"
        },
        {
            "latin_binomial": "Ribes uva-crispa",
            "english_name": "Gooseberry",
            "native_alaskan_name": "Shaax (Tlingit)",
            "native_language": "Tlingit",
            "family": "Grossulariaceae",
            "description": "Deciduous shrub with lobed leaves and tart berries. Available mid-August with a distinct odor. Found in Southeast Alaska.",
            "habitat": "Open forests, forest edges, disturbed areas in Southeast Alaska",
            "traditional_uses": "Berries can be eaten raw. Available mid-August. Has a distinct odor.",
            "parts_used": "Berries",
            "preparation": "Eaten raw. Can be made into jam or jelly.",
            "cautions": "None known. Safe.",
            "verified": True,
            "source_author": "Wikipedia / Telander, Todd (2012)",
            "source_url": "https://en.wikipedia.org/wiki/List_of_edible_plants_and_mushrooms_of_southeast_Alaska"
        },
        {
            "latin_binomial": "Sambucus racemosa",
            "english_name": "Red Elderberry",
            "native_alaskan_name": "Yéil' (Tlingit)",
            "native_language": "Tlingit",
            "family": "Adoxaceae",
            "description": "Tall shrub with compound leaves and clusters of small red berries. Sometimes found up to 20 feet high. Important medicinal and food plant in Southeast Alaska.",
            "habitat": "Forest edges, streambanks, disturbed areas, Southeast Alaska",
            "traditional_uses": "Flowers and mature deseeded fruit can be eaten raw. Cooking the berries removes an alkaloid that may upset the stomach. Said to have the ability to calm nerves.",
            "parts_used": "Flowers, mature berries (cooked)",
            "preparation": "Flowers eaten raw. Berries must be deseeded and cooked to remove stomach-irritating alkaloids. Never eat raw seeds or immature berries.",
            "cautions": "RAW SEEDS AND IMMATURE BERRIES ARE TOXIC. Consumption of seeds, immature berries, stems, and roots can cause nausea and illness. Always cook and deseed berries before eating.",
            "verified": True,
            "source_author": "Wikipedia / Telander, Todd (2012)",
            "source_url": "https://en.wikipedia.org/wiki/List_of_edible_plants_and_mushrooms_of_southeast_Alaska"
        },
        # === Mushrooms from Wikipedia SE Alaska list ===
        {
            "latin_binomial": "Russula xerampelina",
            "english_name": "Shrimp Russula",
            "native_alaskan_name": "Various Southeast names",
            "native_language": "Tlingit",
            "family": "Russulaceae",
            "description": "Edible mushroom with a fishy odor when mature. One of the most commonly eaten russula mushrooms in Southeast Alaska.",
            "habitat": "Temperate rainforest floor, under conifers, Southeast Alaska (Tongass National Forest)",
            "traditional_uses": "Gathered for food. Most commonly eaten russula species in the area. Has a distinctive fishy/shrimp odor when mature.",
            "parts_used": "Mushroom cap, stem",
            "preparation": "Cooked. Can be sautéed, added to soups, or preserved.",
            "cautions": "Must properly identify — some russula species are not edible. Only harvest with experienced mushroom identifiers.",
            "verified": True,
            "source_author": "Wikipedia",
            "source_url": "https://en.wikipedia.org/wiki/List_of_edible_plants_and_mushrooms_of_southeast_Alaska"
        },
        {
            "latin_binomial": "Cantharellus formosus",
            "english_name": "Pacific Gold Chanterelle",
            "native_alaskan_name": "Various Southeast names",
            "native_language": "Tlingit",
            "family": "Cantharellaceae",
            "description": "Large golden mushroom with a distinctive funnel shape and apricot-like odor. Found in small numbers in Southeast Alaska's temperate rainforest. One of the most prized edible mushrooms.",
            "habitat": "Temperate rainforest floor, under conifers, Southeast Alaska (Tongass)",
            "traditional_uses": "Gathered for food. One of the most desirable edible mushrooms in Southeast Alaska. Has an odor similar to apricots.",
            "parts_used": "Mushroom cap, stem",
            "preparation": "Sautéed, added to soups and stews. Can be dried for winter storage.",
            "cautions": "Must properly identify — false chanterelles exist. Only harvest with experienced mushroom identifiers.",
            "verified": True,
            "source_author": "Wikipedia",
            "source_url": "https://en.wikipedia.org/wiki/List_of_edible_plants_and_mushrooms_of_southeast_Alaska"
        },
        {
            "latin_binomial": "Polyozellus multiplex",
            "english_name": "Black Chanterelle / Blue Chanterelle",
            "native_alaskan_name": "Various Southeast names",
            "native_language": "Tlingit",
            "family": "Thelephoraceae",
            "description": "Very distinct and striking mushroom typically found in tight clusters under spruce. Rare in Southeast Alaska. One of the most distinctive mushrooms in the forest.",
            "habitat": "Under spruce, temperate rainforest floor, Southeast Alaska",
            "traditional_uses": "Gathered for food. Very distinct and striking — typically found in tight clusters. Rare and highly prized.",
            "parts_used": "Mushroom",
            "preparation": "Cooked. Sautéed or added to dishes.",
            "cautions": "Rare — do not overharvest. Only harvest with experienced mushroom identifiers.",
            "verified": True,
            "source_author": "Wikipedia",
            "source_url": "https://en.wikipedia.org/wiki/List_of_edible_plants_and_mushrooms_of_southeast_Alaska"
        },
        {
            "latin_binomial": "Boletus mirabilis",
            "english_name": "Admirable Bolete",
            "native_alaskan_name": "Various Southeast names",
            "native_language": "Tlingit",
            "family": "Boletaceae",
            "description": "Large mushroom typically fruiting on wood. Said to have a lemony taste. One of the notable edible boletes in Southeast Alaska.",
            "habitat": "On wood, temperate rainforest, Southeast Alaska",
            "traditional_uses": "Gathered for food. Said to have a lemony taste. Typically fruits on wood.",
            "parts_used": "Mushroom cap",
            "preparation": "Cooked. Sautéed or dried for storage.",
            "cautions": "Must properly identify boletes — some species are bitter or inedible. Only harvest with experienced mushroom identifiers.",
            "verified": True,
            "source_author": "Wikipedia",
            "source_url": "https://en.wikipedia.org/wiki/List_of_edible_plants_and_mushrooms_of_southeast_Alaska"
        },
        {
            "latin_binomial": "Hericium abietis",
            "english_name": "Bear's Head",
            "native_alaskan_name": "Various Southeast names",
            "native_language": "Tlingit",
            "family": "Hericiaceae",
            "description": "Very distinctive fungus that typically grows on conifer logs and stumps. Has a cascading, coral-like or brain-like appearance. One of the most striking mushrooms in Southeast Alaska.",
            "habitat": "Conifer logs and stumps, temperate rainforest, Southeast Alaska",
            "traditional_uses": "Gathered for food. Very distinctive — typically grows on conifer logs and stumps.",
            "parts_used": "Mushroom fruiting body",
            "preparation": "Cooked. Can be sautéed, added to soups, or dried.",
            "cautions": "Must properly identify. Generally safe once identified.",
            "verified": True,
            "source_author": "Wikipedia",
            "source_url": "https://en.wikipedia.org/wiki/List_of_edible_plants_and_mushrooms_of_southeast_Alaska"
        },
        {
            "latin_binomial": "Morchella tomentosa",
            "english_name": "Gray Fire Morel / Black Foot Morel",
            "native_alaskan_name": "Various",
            "native_language": "Multiple",
            "family": "Morchellaceae",
            "description": "Very dark colored morel when young that lightens with age. Considered one of the most desirable edible fungi in the area. Often found after fires or disturbances.",
            "habitat": "Burned areas, disturbed ground, temperate rainforest, Southeast Alaska",
            "traditional_uses": "Gathered for food. One of the most desirable edible fungi. Very dark colored when young, lightens with age.",
            "parts_used": "Mushroom cap",
            "preparation": "Must be cooked thoroughly — never eat raw. Sautéed, dried for storage.",
            "cautions": "MUST BE COOKED THOROUGHLY. Raw morels can cause gastric upset. Must properly identify — false morels (Verpa bohemica) can cause stomach upset.",
            "verified": True,
            "source_author": "Wikipedia",
            "source_url": "https://en.wikipedia.org/wiki/List_of_edible_plants_and_mushrooms_of_southeast_Alaska"
        },
        # === Yup'ik cuisine plant data from Wikipedia ===
        {
            "latin_binomial": "Vaccinium uliginosum",
            "english_name": "Bog Blueberry / Alpine Blueberry",
            "native_alaskan_name": "Various Yupik and Inupiaq names",
            "native_language": "Yupik, Inupiaq",
            "family": "Ericaceae",
            "description": "Low deciduous shrub with small blue-black berries. One of the most important subsistence berries across western and northern Alaska. Used in akutaq (Eskimo ice cream).",
            "habitat": "Bogs, tundra, moist acid soils, lowland and alpine areas across Alaska",
            "traditional_uses": "Berries are one of the most important subsistence foods. Eaten fresh, in akutaq (Eskimo ice cream), or preserved for winter. Mousefood includes roots cached by voles from these plants.",
            "parts_used": "Berries, roots (from mouse caches)",
            "preparation": "Eaten fresh. Mixed with seal oil, sugar, and snow to make akutaq. Dried or frozen for winter storage.",
            "cautions": "None known. Very safe and important food.",
            "verified": True,
            "source_author": "Wikipedia / Yup'ik cuisine article",
            "source_url": "https://en.wikipedia.org/wiki/Yup%CA%BCik_cuisine"
        },
        {
            "latin_binomial": "Rubus chamaemorus",
            "english_name": "Cloudberry / Bakeapple",
            "native_alaskan_name": "Néx'w (Tlingit); Aqpik (Yupik); Akpiq (Inupiaq)",
            "native_language": "Tlingit, Yupik, Inupiaq",
            "family": "Rosaceae",
            "description": "Low perennial herb with palmate leaves and a single amber-orange berry per plant. One of the most prized berries across all of Alaska. Found in boggy and tundra areas.",
            "habitat": "Bogs, tundra, wet meadows across Alaska",
            "traditional_uses": "Berries eaten raw, used in jams and jellies. Leaves used to make medicinal tea. One of the most important berries across all Alaska Native groups. Fruits in late fall.",
            "parts_used": "Berries, leaves",
            "preparation": "Eaten raw, made into jam. Leaves steeped for medicinal tea. Mixed into akutaq.",
            "cautions": "None known. Very safe and highly prized.",
            "verified": True,
            "source_author": "Wikipedia / Telander, Todd (2012) / Yup'ik cuisine",
            "source_url": "https://en.wikipedia.org/wiki/List_of_edible_plants_and_mushrooms_of_southeast_Alaska"
        },
    
        {
            "latin_binomial": "Oplopanax horridus",
            "english_name": "Devil's Club / Devil's Walking Stick / Alaskan Ginseng",
            "native_alaskan_name": "S'áxt' (Tlingit)",
            "native_language": "Tlingit, Haida, Tsimshian",
            "family": "Araliaceae",
            "description": "Large understory shrub native to Pacific Northwest rainforests. Noted for large palmate leaves and erect woody stems covered in noxious, irritating spines. Not a true ginseng but called 'Alaskan ginseng.' Found from southcentral Alaska south to Oregon. One of the most important ceremonial and medicinal plants in Southeast Alaska.",
            "habitat": "Moist dense old-growth conifer forests, rainforest gullies, riparian zones — southcentral Alaska to Oregon",
            "traditional_uses": "Tlingit and Haida used as traditional medicine for adult-onset diabetes and rheumatoid arthritis. Used ceremonially by Tlingit, Tsimshian, and Haida peoples. Charcoal from stalks used for ceremonial and protective face paints. Piece hung over doorways to ward off evil. Used as oral tea, poultices, and ointments. Equally significant as red ochre as a symbolic link to the spirit world.",
            "parts_used": "Bark, stems (charcoal), roots",
            "preparation": "Inner bark tea for diabetes and arthritis. Charcoal from stalks for face paint. Poultices and ointments for external use. Dried and pulverized for various preparations.",
            "cautions": "BERRIES ARE INEDIBLE TO HUMANS. Touching the spiny plant causes skin irritation. The spines are noxious and irritating. Harvest with care — slow growing plant.",
            "verified": True,
            "source_author": "Wikipedia / NPR (Levine, 2004) / USFS",
            "source_url": "https://en.wikipedia.org/wiki/Devil%27s_club"
        },
        {
            "latin_binomial": "Salix alaxensis",
            "english_name": "Feltleaf Willow / Alaska Willow",
            "native_alaskan_name": "Various Athabascan and Inupiaq names",
            "native_language": "Athabascan (multiple), Inupiaq, Yupik",
            "family": "Salicaceae",
            "description": "Species of willow native to northern North America, occurring throughout Alaska and northwestern Canada. Recognized by its felt-like silvery leaves. One of the most widespread and important willows across Alaska.",
            "habitat": "Riverbars, floodplains, disturbed areas, open areas throughout Alaska",
            "traditional_uses": "Bark contains salicin (natural aspirin precursor) — used for pain relief and fever reduction. Young shoots eaten in spring. Branches used in basketry and construction. Important medicinal plant across all Alaska Native groups.",
            "parts_used": "Bark, young shoots, branches",
            "preparation": "Bark tea for pain and fever (natural aspirin). Young shoots collected in spring as vegetable. Branches used for baskets and structures.",
            "cautions": "Contains salicin — similar to aspirin. Should not be used by those sensitive to aspirin. Safe in traditional amounts.",
            "verified": True,
            "source_author": "Wikipedia / USFS Fire Effects Information System (Uchytil, 1991)",
            "source_url": "https://en.wikipedia.org/wiki/Salix_alaxensis"
        },
        {
            "latin_binomial": "Gaultheria shallon",
            "english_name": "Salal / Shallon",
            "native_alaskan_name": "Various Southeast Alaska names",
            "native_language": "Tlingit, Haida",
            "family": "Ericaceae",
            "description": "Evergreen shrub in the heather family native to western North America. Found in Southeast Alaska's temperate rainforest. Produces dark purple-black berries that are sweet and flavorful.",
            "habitat": "Temperate rainforest understory, forest openings, coastal areas — Southeast Alaska",
            "traditional_uses": "Berries are an important food in Southeast Alaska — eaten fresh, dried, or made into preserves. One of the most abundant berries in the Tongass National Forest. Leaves used medicinally.",
            "parts_used": "Berries, leaves",
            "preparation": "Berries eaten fresh, dried, or made into jam. Leaves steeped as tea.",
            "cautions": "None known. Very safe and important food plant.",
            "verified": True,
            "source_author": "Wikipedia / Wild edible and medicinal plants of British Columbia",
            "source_url": "https://en.wikipedia.org/wiki/Gaultheria_shallon"
        },
        {
            "latin_binomial": "Amelanchier alnifolia",
            "english_name": "Saskatoon Berry / Pacific Serviceberry / Western Serviceberry / Western Juneberry",
            "native_alaskan_name": "Various Interior and Southcentral names",
            "native_language": "Athabascan (multiple)",
            "family": "Rosaceae",
            "description": "Shrub native to North America, member of the rose family. Bears edible berry-like fruit. Found in Interior and Southcentral Alaska. One of the earliest berries to ripen.",
            "habitat": "Open forests, hillsides, dry slopes, forest edges — Interior and Southcentral Alaska",
            "traditional_uses": "Berries are an important early-season food — eaten fresh, dried, or made into preserves. One of the first berries available in summer. Wood used for arrows and tools.",
            "parts_used": "Berries, wood",
            "preparation": "Berries eaten fresh, dried for winter, or made into jam. Wood used for arrows and implements.",
            "cautions": "None known. Very safe food plant.",
            "verified": True,
            "source_author": "Wikipedia",
            "source_url": "https://en.wikipedia.org/wiki/Amelanchier_alnifolia"
        },
        {
            "latin_binomial": "Picea glauca",
            "english_name": "White Spruce / Canadian Spruce",
            "native_alaskan_name": "Ts'uu (Dena'ina); various Athabascan names",
            "native_language": "Dena'ina, Athabascan (multiple), Inupiaq, Yupik",
            "family": "Pinaceae",
            "description": "Large coniferous tree dominant in Interior Alaska's boreal forest. One of the most culturally important trees across Alaska — used for medicine, food, shelter, tools, and fuel. Maximum tree line at about 4,000 feet.",
            "habitat": "Boreal forest, well-drained soils, river terraces, lowlands — Interior and Southcentral Alaska",
            "traditional_uses": "Inner bark eaten as emergency food. Spruce tips (new growth) collected in spring for tea rich in vitamin C. Pitch/resin used as wound sealant and medicine. Wood used for construction, snowshoes, and tools. Roots used for basketry. Tanana Athabaskans use birch bark baskets made from spruce for storage.",
            "parts_used": "Inner bark, young tips, pitch/resin, wood, roots",
            "preparation": "Spruce tip tea in spring (high vitamin C). Inner bark scraped and eaten fresh or dried. Pitch applied to wounds as antiseptic sealant. Wood for construction and tools.",
            "cautions": "None known for traditional uses. Do not consume large amounts of resin internally.",
            "verified": True,
            "source_author": "Wikipedia: Tanana Athabaskans / Garibaldi (1999) / Kari (1987)",
            "source_url": "https://en.wikipedia.org/wiki/Tanana_Athabaskans"
        },
        {
            "latin_binomial": "Picea mariana",
            "english_name": "Black Spruce / Bog Spruce",
            "native_alaskan_name": "Ts'uu tseh (Dena'ina); various",
            "native_language": "Dena'ina, Athabascan (multiple)",
            "family": "Pinaceae",
            "description": "Small to medium coniferous tree found in wet, boggy areas across Alaska. Often stunted in growth. Co-dominant with white spruce in Interior Alaska's boreal forest.",
            "habitat": "Bogs, muskegs, wet lowland soils, permafrost areas — Interior and Northern Alaska",
            "traditional_uses": "Used similarly to white spruce for medicine and materials. Pitch used medicinally. Wood used for construction where available. Important in areas where white spruce doesn't grow.",
            "parts_used": "Pitch/resin, young tips, wood",
            "preparation": "Pitch for wound sealant. Tip tea for vitamin C. Wood for construction.",
            "cautions": "None known for traditional uses.",
            "verified": True,
            "source_author": "Wikipedia: Tanana Athabaskans / Garibaldi (1999)",
            "source_url": "https://en.wikipedia.org/wiki/Tanana_Athabaskans"
        },
        {
            "latin_binomial": "Betula neoalaskana",
            "english_name": "Alaska Birch / Yukon Birch",
            "native_alaskan_name": "K'ch' (Dena'ina); various Athabascan names",
            "native_language": "Dena'ina, Athabascan (multiple)",
            "family": "Betulaceae",
            "description": "Deciduous tree found across Interior Alaska. One of the most culturally important trees — bark used for baskets, baby carriers, and canoes. Sap collected in spring as tonic. Tanana Athabaskans are renowned for birch bark basketry.",
            "habitat": "Well-drained soils, river terraces, south-facing slopes — Interior Alaska",
            "traditional_uses": "Bark used for baskets, baby carriers, and canoes (Tanana Athabaskans renowned for this). Sap collected in spring as sweet tonic. Wood used for snowshoes and fuel. Fungus growing on birch (chaga) used medicinally.",
            "parts_used": "Bark, sap, wood",
            "preparation": "Bark carefully peeled and shaped into baskets. Sap collected in spring by tapping. Wood for snowshoes and tools.",
            "cautions": "None known for traditional uses. Harvest bark sustainably — removing bark in a ring kills the tree.",
            "verified": True,
            "source_author": "Wikipedia: Tanana Athabaskans / Susan W. Fair (Birch bark basketry)",
            "source_url": "https://en.wikipedia.org/wiki/Tanana_Athabaskans"
        },
        {
            "latin_binomial": "Alnus viridis",
            "english_name": "Green Alder / Mountain Alder / Sitka Alder",
            "native_alaskan_name": "Various Athabascan names",
            "native_language": "Athabascan (multiple), Tlingit",
            "family": "Betulaceae",
            "description": "Deciduous shrub or small tree found across Alaska. Only stunted willows and alders grow above the tree line (around 4,000 feet). Important pioneer species in disturbed areas.",
            "habitat": "Streambanks, moist slopes, disturbed areas, above tree line — throughout Alaska",
            "traditional_uses": "Bark used medicinally as astringent and for skin conditions. Wood used for smoking fish. Nitrogen-fixing species important for soil health. Alder thickets provide important berry-picking habitat.",
            "parts_used": "Bark, wood",
            "preparation": "Bark tea as astringent for skin conditions. Wood for smoking fish and fuel.",
            "cautions": "None known for traditional uses.",
            "verified": True,
            "source_author": "Wikipedia: Tanana Athabaskans / Garibaldi (1999)",
            "source_url": "https://en.wikipedia.org/wiki/Tanana_Athabaskans"
        },
        {
            "latin_binomial": "Ligusticum scoticum",
            "english_name": "Scottish Licorice Root / Beach Lovage",
            "native_alaskan_name": "Various coastal names",
            "native_language": "Tlingit, Aleut/Unangan",
            "family": "Apiaceae",
            "description": "Perennial herb in the carrot family found on coastal beaches and cliffs. The leaves and stems have a strong celery-like flavor. Found in coastal Alaska.",
            "habitat": "Coastal beaches, cliffs, rocky shores — coastal Alaska",
            "traditional_uses": "Leaves and young stems eaten as a potherb or raw vegetable. Roots used medicinally. One of the important coastal wild greens in Alaska.",
            "parts_used": "Leaves, stems, roots",
            "preparation": "Leaves eaten raw or cooked. Roots used as condiment and medicine.",
            "cautions": "Must correctly identify — some members of Apiaceae are toxic. Do not confuse with water hemlock.",
            "verified": True,
            "source_author": "Wikipedia / Schofield, Janice J. (1993)",
            "source_url": "https://en.wikipedia.org/wiki/Ligusticum_scoticum"
        },
        {
            "latin_binomial": "Cetraria islandica",
            "english_name": "Iceland Moss / Iceland Lichen",
            "native_alaskan_name": "Various Arctic names",
            "native_language": "Inupiaq, Yupik, Athabascan",
            "family": "Parmeliaceae",
            "description": "Lichen found across Arctic and boreal regions including Alaska. A traditional food and medicine across northern cultures. One of the most important lichens in Arctic Alaska.",
            "habitat": "Tundra, barren ground, alpine areas, heaths — Arctic and alpine Alaska",
            "traditional_uses": "Used as food and medicine across Arctic peoples. Boiled or steeped as tea for respiratory complaints. Nutritious emergency food. Also used as a thickening agent in soups.",
            "parts_used": "Whole lichen (thallus)",
            "preparation": "Boiled thoroughly to remove bitterness, then eaten. Steeped as tea for respiratory complaints. Dried and ground for storage.",
            "cautions": "Raw lichen is bitter and can cause stomach upset — must be boiled or soaked. Safe after proper preparation.",
            "verified": True,
            "source_author": "Wikipedia / Garibaldi (1999)",
            "source_url": "https://en.wikipedia.org/wiki/Cetraria_islandica"
        },
        {
            "latin_binomial": "Cladonia rangiferina",
            "english_name": "Reindeer Lichen / Reindeer Moss",
            "native_alaskan_name": "Various Arctic names",
            "native_language": "Inupiaq, Yupik, Gwich'in",
            "family": "Cladoniaceae",
            "description": "Highly branched lichen found in Arctic and boreal regions. A key winter food for caribou/reindeer — hence the name. Found abundantly across Alaska's tundra and boreal forest.",
            "habitat": "Tundra, boreal forest floor, sandy soils, open areas — across Alaska",
            "traditional_uses": "Emergency food source when properly prepared. Important ecological species — primary winter food for caribou, which are culturally essential to Gwich'in and Inupiaq peoples. Used as insulation in footwear.",
            "parts_used": "Whole lichen (thallus)",
            "preparation": "Must be soaked and boiled to remove acids before eating. Crushed and used as insulation. Not a preferred food but important emergency sustenance.",
            "cautions": "Contains usnic acid and other compounds — must be properly prepared. Raw consumption can cause stomach upset.",
            "verified": True,
            "source_author": "Wikipedia / Gwich'in ethnobotany (2002)",
            "source_url": "https://en.wikipedia.org/wiki/Cladonia_rangiferina"
        },
        {
            "latin_binomial": "Fucus gardneri",
            "english_name": "Bladderwrack / Rockweed / Pacific Rockweed",
            "native_alaskan_name": "Various coastal names",
            "native_language": "Tlingit, Haida, Aleut/Unangan",
            "family": "Fucaceae",
            "description": "Brown seaweed found on rocky shores throughout coastal Alaska. One of the most common seaweeds in Southeast Alaska. Important source of iodine and minerals.",
            "habitat": "Rocky intertidal shores, protected coastlines — coastal Alaska",
            "traditional_uses": "Eaten as vegetable and medicine. Important source of iodine, calcium, and minerals. Tlingit gather seaweed on the beach and cook it over fire or boil it. Used in soups and stews.",
            "parts_used": "Whole seaweed (thallus)",
            "preparation": "Eaten fresh, dried for storage, or added to soups and stews. Can be roasted or boiled.",
            "cautions": "Generally safe. High iodine content — excessive consumption may affect thyroid function.",
            "verified": True,
            "source_author": "Wikipedia: Tlingit cuisine / Schofield (1993)",
            "source_url": "https://en.wikipedia.org/wiki/Tlingit_cuisine"
        },
        {
            "latin_binomial": "Saccharina latissima",
            "english_name": "Sugar Kelp / Sweet Kelp / Sea Belt",
            "native_alaskan_name": "Various coastal names",
            "native_language": "Tlingit, Haida, Aleut/Unangan, Sugpiaq/Alutiiq",
            "family": "Laminariaceae",
            "description": "Large brown kelp found in coastal Alaska waters. One of the most important seaweeds in Alaska Native cuisine. Tlingit use hemlock branches and kelp to harvest herring eggs — a delicacy called 'Tlingit caviar.'",
            "habitat": "Subtidal zones, sheltered coastal waters — throughout coastal Alaska",
            "traditional_uses": "Eaten as vegetable. Used as substrate for herring egg harvest (herring spawn on kelp — a delicacy). Dried for winter storage. Rich in vitamins and minerals.",
            "parts_used": "Frond (blade)",
            "preparation": "Eaten fresh, dried for winter, or used in soups. Kelp submerged in herring spawning areas to collect eggs. Dried kelp used in various dishes.",
            "cautions": "Generally safe. High iodine content — excessive consumption may affect thyroid function.",
            "verified": True,
            "source_author": "Wikipedia: Tlingit cuisine / Herring eggs on kelp",
            "source_url": "https://en.wikipedia.org/wiki/Tlingit_cuisine"
        },
        {
            "latin_binomial": "Sagittaria latifolia",
            "english_name": "Wapato / Arrowhead / Duck Potato",
            "native_alaskan_name": "Various Southeast names",
            "native_language": "Tlingit, Haida",
            "family": "Alismataceae",
            "description": "Aquatic perennial with edible tubers. Found in shallow waters and wetlands. Tubers are starchy and potato-like. Important root food in Southeast Alaska and the Pacific Northwest.",
            "habitat": "Shallow water, marshes, wetlands, pond edges — Southeast Alaska",
            "traditional_uses": "Tubers are an important starchy root food — harvested by wading into mud and freeing them with feet. Eaten boiled, roasted, or dried. One of the few starchy root foods in the region.",
            "parts_used": "Tubers",
            "preparation": "Boiled, roasted, or dried for storage. Can be ground into flour.",
            "cautions": "None known. Very safe food plant.",
            "verified": True,
            "source_author": "Wikipedia / Wild edible and medicinal plants of British Columbia",
            "source_url": "https://en.wikipedia.org/wiki/Wild_edible_and_medicinal_plants_of_British_Columbia"
        },
        {
            "latin_binomial": "Trifolium wormskioldii",
            "english_name": "Springbank Clover / Cow Clover",
            "native_alaskan_name": "Various Southeast names",
            "native_language": "Tlingit, Haida",
            "family": "Fabaceae",
            "description": "Perennial clover found in coastal meadows and damp areas. Roots are edible and were an important food source in the Pacific Northwest including Southeast Alaska.",
            "habitat": "Coastal meadows, damp ground, streambanks — Southeast Alaska",
            "traditional_uses": "Roots are edible and were an important starchy food. Harvested in late summer. One of the few root vegetables traditionally available in Southeast Alaska.",
            "parts_used": "Roots",
            "preparation": "Roots steamed or boiled. Can be dried and stored for winter.",
            "cautions": "None known. Safe food plant.",
            "verified": True,
            "source_author": "Wikipedia / Wild edible and medicinal plants of British Columbia",
            "source_url": "https://en.wikipedia.org/wiki/Wild_edible_and_medicinal_plants_of_British_Columbia"
        },
        {
            "latin_binomial": "Malus fusca",
            "english_name": "Wild Crabapple / Pacific Crab Apple / Oregon Crabapple",
            "native_alaskan_name": "Various Southeast names",
            "native_language": "Tlingit, Haida",
            "family": "Rosaceae",
            "description": "Small tree or shrub with edible but tart fruit. Found in Southeast Alaska coastal forests. One of the few tree fruits native to Alaska.",
            "habitat": "Coastal forests, streambanks, moist areas — Southeast Alaska",
            "traditional_uses": "Fruit eaten fresh, cooked, or preserved. Important late-season fruit source in Southeast Alaska. Used in jams and jellies.",
            "parts_used": "Fruit",
            "preparation": "Eaten fresh (very tart), cooked, or made into jam and jelly.",
            "cautions": "None known. Very tart — usually cooked or sweetened.",
            "verified": True,
            "source_author": "Wikipedia / Wild edible and medicinal plants of British Columbia",
            "source_url": "https://en.wikipedia.org/wiki/Wild_edible_and_medicinal_plants_of_British_Columbia"
        },
        {
            "latin_binomial": "Ribes bracteosum",
            "english_name": "Stink Currant / California Black Currant",
            "native_alaskan_name": "Various Southeast names",
            "native_language": "Tlingit",
            "family": "Grossulariaceae",
            "description": "Deciduous shrub with large maple-like leaves and clusters of dark berries. Found in Southeast Alaska. Berries have a strong odor but are edible.",
            "habitat": "Moist forests, streambanks, ravines — Southeast Alaska",
            "traditional_uses": "Berries eaten despite strong odor. Used in preserves. An important berry variety in Southeast Alaska.",
            "parts_used": "Berries",
            "preparation": "Eaten fresh or cooked. Made into jam and jelly.",
            "cautions": "Strong odor — some find them unpalatable fresh. Safe to eat.",
            "verified": True,
            "source_author": "Wikipedia / Wild edible and medicinal plants of British Columbia",
            "source_url": "https://en.wikipedia.org/wiki/Wild_edible_and_medicinal_plants_of_British_Columbia"
        },
    
    ]

    count = 0
    for plant_data in plants:
        add_plant(**plant_data)
        count += 1

    return count


if __name__ == "__main__":
    import sys
    sys.path.insert(0, os.path.dirname(__file__))
    from database import init_database
    init_database()
    seeded = seed_verified_plants()
    print(f"Seeded {seeded} verified Alaskan Native botanicals.")
